[package]
name = "rustdar-gps"
version.workspace = true
edition.workspace = true

[features]
default = ["serial"]
serial = ["dep:serialport"]

[dependencies]
chrono = "=0.4.44"
log = "=0.4.33"
nmea = "=0.6.0"
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.149"
serialport = { version = "=4.9.0", optional = true }
