pub mod archive;
pub mod beam;
pub mod chunks;
pub mod current;
pub mod derive;
pub(crate) mod dpprep;
pub mod eet;
pub mod hail;
pub mod hca;
pub mod hhc;
pub mod kdp;
pub(crate) mod l3_values;
pub mod level3;
pub mod nrot;
pub mod nyquist;
mod palette;
pub(crate) mod par;
pub mod render;
pub mod render_input;
pub mod sampler;
pub mod scan;
pub mod sites;
pub mod sounding;
pub mod sources;
pub mod srm;
pub mod srv;
pub mod tls;
pub mod twin;
pub mod types;
pub mod vil;
pub mod vild;
pub mod volumetric;
pub mod voxel;
pub mod xsect;

pub use palette::{LegendScale, get_color_for_value, get_legend_scale};
