name: Clippy
on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref }}'
  cancel-in-progress: true

jobs:
  clippy:
    name: Clippy
    runs-on: rustdar-runner-set
    permissions:
      contents: write
    steps:
      - name: Generate GitHub App Token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: app-token
        with:
          client-id: ${{ secrets.AUTO_COMMIT_APP_ID }}
          private-key: ${{ secrets.AUTO_COMMIT_APP_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy

      - name: Install ALSA
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --fix || true
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "chore: Apply clippy fixes"
          commit_user_name: usa-reddragon-auto-commit[bot]
          commit_user_email: 234130638+github-actions[bot]@users.noreply.github.com
          commit_author: "usa-reddragon-auto-commit[bot] <234130638+github-actions[bot]@users.noreply.github.com>"
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
